### ISSUE TITLE
Joystick Gremlin Crash, won't re-open

### ISSUE THREAD

**Issue by Meekstaaa** [WhiteMagic/JoystickGremlin#111]
Hi,

Just a heads up really.

When I have Gremlin crash (usually crashes when I edit stuff with a game open). It won't re-open gremlin until I restart my PC. Don't think I'm doing anything wrong (I've closed any hung processes in the task manager before reopening).

**Comment by WhiteMagic** [comment]
If you look in the logs, Tools -> Log Viewer or %userprofile%/Joystick Gremlin/system.log, do you see "Unknown Device" or similar where it lists your other devices? I've had Gremlin do something similar to me random occasions and it seems to be SDL2 (library used to read joystick data) somehow failing to pick up one or more vJoy devices which ends up breaking everything.

I haven't figure out why that happens or what causes it. I've had either to reboot or remove the vJoy devices and then readd them via the vjoy config utility.

Also Gremlin crashing when you edit stuff shouldn't really be a thing anything in particular standing out that could pinpoint what is causing it, or what it is you have to do to get it to crash?

**Comment by Meekstaaa** [comment]
Hi,

I do not see any of those errors in the log file (I've attached it for you to have a look at).

It looks like last night when I was trying to edit it during a game it corrupted the profile as after that it would crash straight away as soon as I tried to activate the profile. Also when starting up the PC it would show a warning message saying it failed to activate the profile.

I created a new profile and it worked again fine. I also kept having the crash randomly during testing and would activate but not load (you can see in the log there are multiple times the system starts but nothing else happens).

When not editing it works fine.

[system.log](https://github.com/WhiteMagic/JoystickGremlin/files/2063074/system.log)

**Comment by WhiteMagic** [comment]
Looking through the log I think there might be two issues. One is when it simply states how many joysticks it found but nothing else, which I assume is where it crashes which is a different issue then the one I've been seeing but in the same area, i.e. initializing joystick stuff.

The other crashes could be due to you using the regex to have Gremlin activate on boot. The side effect is that it will deactivate and reactivate each time the active process changes (if I remember the logic I coded for that bit correctly). That will switch things quickly and might be the reason for the crashes when you're making changes to the config. While this shouldn't be causing crashes I wouldn't be surprised if it can lead to some as I haven't used Gremlin in this fashion. I'll have to see if I can get it to misbehave when using it with auto activation on everything.

**Comment by Meekstaaa** [comment]
Hi again,

Not sure if all the crashs is due to the regedit activate. I have a shortcut in the start folder with the activate action on it but the one I use for restarts doesn't have that on it. 

Not sure if using the way I have it set can affect the main exe or not.

Can't remember if I told you this, but when it crashes I can't seem to always get it to restart. The process is closed then I go to restart and it loads the process and that's all. Looking at the log again looks like it does the load joystick thing and nothing else. Sometimes closing again and re-opening works, others I have to restart the PC. Attaching another log if that's any help.


[system.log](https://github.com/WhiteMagic/JoystickGremlin/files/2067947/system.log)

**Comment by WhiteMagic** [comment]
Closing this for now, but feel free to reopen or create a new issue if this persists. Some of those crashing issues should be resolved in R13.
