### ISSUE TITLE
HidGuardian doesn't seem to work with bluetooth devices?

### ISSUE THREAD

**Issue by Zriel88** [WhiteMagic/JoystickGremlin#119]
As said, I have an xbox one bluettoth controller, which I'm trying to setup with Joystick gremlin for playing xwing alliance.
Everything is working correctly so far, but game still detects the axis of the hardware controller.
So I read about the hidguardian feature, used it, but doesn't seem to take any effect (I can still see the controller on the game devices control panel in windows).

I can't remapp axis on the game, so thus the need for this feature.

**Comment by WhiteMagic** [comment]
I'm unsure how HidGuardian works with bluetooth devices and it may indeed only be designed to intercept USB devices. Just in case you haven't done this yet, whenever a device is added to HidGuardian for blocking or no longer blocking that device needs to be unplugged and plugged back in. The newer version of HidGuardian Nefarius is working on may solve this and other issues but from what I know it's still being developed and debugged.

If the main thing that's preventing you from using the xbox controller in-game is the inability to map inputs because the game sees both, then you can also use the Tool -> Input Repeater tool. What this will do is repeat your last action after a short pause, thus ensuring the game only sees the virtual inputs. So the work flow is something like this:
1. Press button / move axis on the physical device
1. Enter the remapping dialog for the desired action in-game, i.e. make it listen for inputs
1. After a short delay of no other physical inputs Gremlin will repeat your last action which the game should pick up

**Comment by Zriel88** [comment]
Yeah, I have powered off/on the device, no luck
I can't map axxis in the game, only buttons.
In any case, I've found a fix for this. Launching the game without the gamepad active will detect only the vjoy, and later I can power on the gamepad and all works as intended. 
A question, I have seen under Device information, the system ID. Vjoy is detected as 0 and the hardware gamepad is detected as 1.
From what I read I would say this System ID would start at 1. I am mistaken?

**Comment by WhiteMagic** [comment]
Ah yeah the trick with turning on the physical device only after the game is running usually works well with games that don't detect new devices at runtime.

The hardware id is kind of misleading. I initially assumed this would be the same ID as the one windows assigns devices, however, what this value is in reality is the internal ID assigned to that device by SDL, the library I use to read device information. So at times this can differ greatly from the windows order (when there is a lot of plugging and unplugging of devices mainly) but is the id Gremlin uses when differentiating between multiple identical devices.

I've been thinking on and off of how to make this behaviour a bit less confusing or possibly find a way to not ever need an additional identifier but so far I haven't found something simple or the time to do something complex about it.
