### ISSUE TITLE
Simulate Analog-Like Behavior for Digital Button

### ISSUE THREAD

**Issue by djscott00** [WhiteMagic/JoystickGremlin#120]
Some games can be problematic in that they have certain actions that would benefit from an analog input, but don't actually permit you to rebind the action to an analog control. One possible workaround for this is to rapidly depress/release the button with some varying frequency.

I think it would be fantastic if Joystick Gremlin supported this sort of behavior natively, where moving the stick further from the center will result in the mapped button being depressed more, and being released less.

I wrote an Autohotkey script that does just this and seems to work very well, but I can't run it alongside Joystick Gremlin as I imagine there's some conflicts with with two processes trying to drive vjoy. I'd rather use Joystick Gremlin instead of trying to replicate everything in Autohotkey, so here's a feature request instead.

I thought about a custom module in Joystick Gremlin, but it seems like it's only going to trigger when there's a change in the stick position, so wouldn't be so useful if you're maintaining a particular stick value? Or is there a good way to just have a continual loop in a custom module that won't break anything?

Here's a video of the Autohotkey script in action: https://youtu.be/CwKiqXXDMKY

Here's the quick and dirty Autohotkey script that can definitely be done in a more graceful manner, but get's the general idea across: [GTA5_yaw.ahk.txt](https://github.com/WhiteMagic/JoystickGremlin/files/2083132/GTA5_yaw.ahk.txt)
(it has a dependency on https://github.com/evilC/AHK-CvJoyInterface )

I loooooove Joystick Gremlin. Thanks so much for the continuing development on it.

**Comment by WhiteMagic** [comment]
A custom module can do this in many different ways one way would be to use the `periodic` decorator to have a function run at a fixed frequency which then presses and releases buttons based on a schedule which is defined by the axis state.

I've written an example of what this could look like here https://gist.github.com/WhiteMagic/8d4b495d30f29213cbfa9df2478e2dfe It's not the prettiest or most efficient way of doing it and  it may also not work for every game, based on how they actually handle velocity inputs via buttons.

I'm currently a bit weary of adding new core actions to Gremlin mainly because a lot of them are quite specific and hard to make into general purpose actions similar to remap, macro, etc. Mainly I first want to finish the reworked custom module system, which will allow the creation of custom modules that are user configurable from within the UI. I hope that that would becomes a better solution for these actions that are uncommon but not one off things, so that they can be shared much easier.

**Comment by djscott00** [comment]
Thanks a bunch. That example module helped point me in the right direction.

**Comment by WhiteMagic** [comment]
Awesome, if you have any questions just let me know.

**Comment by djscott00** [comment]
Only thing that became a bit of an issue was trying to get the current mode from within the repeating function. I basically wanted to return early in the function if the current mode wasn't my "Piloting" mode. I see that the ModeList class has a "_current_index" value, but I didn't seem to be able to retrieve that.

The workaround that I ended up doing is just having a joystick decorator for each of my modes, and setting the global g_current_velocity value to 0 for the modes that I didn't want any action taken place.

The other workaround I thought about was basically just handling mode switching in the custom module itself like in your "Mode Switching" example.

**Comment by WhiteMagic** [comment]
You should be able to retrieve the currently active mode from the EventHandler class in gremlin/event_handler.py, i.e.
```
import gremlin.event_handler

# Somewhere later on
current_mode = gremlin.event_handler.EventHandler().active_mode
```
The EventHandler class is a singleton so there is no special setup or similar needed. I'm also looking into adding callbacks that trigger when a mode switch occurs as that is something that is at times needed to do cleanup / synchronization etc.

**Comment by djscott00** [comment]
That works perfectly. Thanks again!

**Comment by Stumpii** [comment]
I know this is an old thread, but @djscott00 can you share this code? I am looking to write the same plugin at the moment.
