### ISSUE TITLE
Response curve Diagonal Symetry

### ISSUE THREAD

**Issue by Francky63** [WhiteMagic/JoystickGremlin#126]
If Diagonal Symetry is check and then you move away from the form without to save profile when you return back to axis profile the flag is no more checked and sometimes the flag is checked but the curve is not symetrical

**Comment by Francky63** [comment]
"sometimes the flag is checked but the curve is not symetrical" this it happen when curve type is changed

**Comment by WhiteMagic** [comment]
Not persisting whether or not a curve was created using the symmetry option is expected, as I don't store that information anywhere. The reason is that I consider the symmetry option as a tool to ease the creation of curves and not a property of the curve itself.

The UI retaining the symmetry checkbox is caused by me not clearing the settings properly when changing the curve type. That's easy enough to fix so I should get around to that soon I hope.

**Comment by WhiteMagic** [comment]
Symmetry mode checkbox is properly resetting now when switching between curve styles (29bc89b906926e1589b7ce237ce47f5d47e6bd8f)
