### ISSUE TITLE
Importing external Python libraries?

### ISSUE THREAD

**Issue by Lombra** [WhiteMagic/JoystickGremlin#131]
Hi,

I'm looking to integrate websockets in order to interface with a game API and make some interesting stuff. Is it possible to import arbitrary Python libraries into a custom module?

If not, is this something you would consider implementing? Or is there any other way to extend the application to make such things possible?

**Comment by WhiteMagic** [comment]
You should be able to do this now using the custom modules. They are just python code which Gremlin imports upon activation. The main issue that I can foresee is that Gremlin uses its own bundled Python runtime and packages.

So in order to get websockets working, or any other python package, you will have to place them somewhere where they can be found and imported by Gremlin during runtime. Currently there is nothing that allows you to inform Gremlin of additional folders to look for importable content. However, Gremlin automatically adds the folder where your custom module lives to the PYTHON_PATH in order to properly import the custom module. You can (ab)use this to import arbitrary modules.

So if you have a structure such as:
```
|- Root folder/
|  |- custom_module.py
|  |- websockets/
|  |  |- __inity__.py
|  |  |- ...
```
and you load the custom_module.py as custom module into python the entire `Root folder` will be considered for future imports of other content. Thus you can then do `import websockets` inside the custom_module.py file to import that module. Depending on the what additional bits the packages you use require you may have to put a bunch of things into the folder to ensure everything can be imported successfully.

Depending on how complex the additional code you want to develop is, it might be worthwhile doing that development using the source version of Gremlin rather then the packaged one, as that way you can use a proper IDE and get more meaningful information on code errors etc.

**Comment by WhiteMagic** [comment]
No, it should not normally crash. Typically it should just throw up an error when there is an error in the script, as that will cause the import statement to fail. However, quite a few things can go horribly wrong in custom scripts so I am not surprised that it is possible to crash Gremlin with that. That's why I mentioned that doing this type of development via the IDE might be easier, as it would allow you to see when the crash happens and figure it out without having to blindly stab at things that might cause it.

**Comment by Lombra** [comment]
Hm, ok. It seems to crash from just about any error, though. Basic syntax and reference errors.

For example this code crashes it: (not importing gremlin)
`gremlin.util.log("hi")`

**Comment by WhiteMagic** [comment]
I think I know what could cause that but it's nothing that can be fixed via a config etc. You can try this version https://www.dropbox.com/s/88ac1rj8b9y4k1x/Joystick.Gremlin.R11.Debug3.zip?dl=0 which worked for me when testing it with broken imports etc. It might have other issues as it was a build made to test some other problems someone else had.

**Comment by Lombra** [comment]
Yes! That version works. Thanks. :)

I noticed a minor related bug. I can open a new ticket if you prefer, but the "Activate" button appears as though the profile is active even when an error was thrown.

**Comment by WhiteMagic** [comment]
This is not actually a bug but it might be confusing so maybe needs changing. Whenever Gremlin throws an exception that is unhandled, resulting in the error dialog, it pauses itself. This is indicated by the red "Paused" in the bottom left corner which normally shows "Active". The reason Gremlin does this is to prevent the user getting spammed by errors if the function causing them gets triggered a lot.

Though as few people use the pause functionality and thus no one is aware to look down in the bottom corner for that info, but rather only the icon it might be worth changing the pausing behaviour to a deactivation behaviour on exceptions. Alternatively or in addition having the icon change color from green to orange, change the icon shape, or similar when paused couldn't hurt either

**Comment by Lombra** [comment]
Hm, I am not seeing "Paused" anywhere. The gamepad icon turns green, the tray icon has the red little dot, but status in bottom left says "Not running". Possibly related to aforementioned crashes?

**Comment by WhiteMagic** [comment]
Hm that's odd, it should pause everything instead of turning itself off ... unless I've changed that in some in between version at some stage. I'll have to look into that.
