### ISSUE TITLE
Map to Axis

### ISSUE THREAD

**Issue by Carlton2001** [WhiteMagic/JoystickGremlin#132]
Hi,

We currently have **Map to Keyboard** and **Map to Mouse** (works very well) but I'm missing **Map to Axis**.
I'm sure this can be done with a custom module but I can't code this myself.
This could be a nice addition to the GUI, it would offer the possibility to emulate another vjoy axis with two buttons.
With the macro system we can set an axis to an absolute position but we can't "rotate" the axis.

Also I could see a simple if, then, else implementation in the GUI but with global variables we can define. I think this is an other story ^^.

Thanks for your work WhiteMagic !

**Comment by WhiteMagic** [comment]
The main reason there isn't a map to axis action yet is that Gremlin's UI is what could be called input focused. Essentially all actions are created associated with the inputs they should be triggered by. This makes actions that are configured by or use multiple physical inputs a bit awkward from a UI side. This is evident by the merge axis functionality being hidden away in a menu.

The other way of organizing the UI would be action centric, i.e. you select the action you want to perform and then assign the physical inputs used to trigger those. I think UCR could be classified as using that method.

In my opinion both have advantages and disadvantages for Gremlin I didn't really make a conscious decision about this in the beginning, it just seemed nicer to me to have devices in separate tabs which then lead to this input centric UI. Every now and then I tried coming up with a way to have such "multi input" actions present in the current UI scheme but so far I haven't found something that I think would work, which is why things like merge axis is still hidden away in its menu.

Adding a relative axis change to the macro system definitely is something useful and isn't even that hard to add, so that's definitely going to happen. There is also the feature that I am fighting with at the moment which aims to make writing reusable custom modules possible by exposing configuration parameters of these custom modules to the UI. So a "map_to_axis.py" custom module would be written once with four parameters

- axis to control
- increment button
- decrement button
- step size

This anyone could then load into Gremlin and configure it as they like, and if this is needed for more then one axis multiple copies can be used. This should make these modules much more useful as they'd be written once and then others that have a use for them, but use different devices or setups, can configure them without having to change code.

With regards to adding conditional statements into the UI, I'm kind of hesitant of doing this, as that is a whole lot of UI madness for something where a simple custom module would be a million times better due to being simpler to create and understand. I think it would be much more beneficial to invest the time needed to implement such a feature into better documentation / tutorials on how to write such a module and make it easier to develop / debug them. Currently writing them is a bit tedious as any error causes an exception and there are no good tools there to help you develop them.

**Comment by WhiteMagic** [comment]
Macros can now be used to set a vJoy axis value incrementally, thus enabling the creation of such a map to axis action.
