### ISSUE TITLE
Current download detected by Windows Defender as a threat

### ISSUE THREAD

**Issue by ventorvar** [WhiteMagic/JoystickGremlin#178]
The current (R12) download from the official site (https://whitemagic.github.io/JoystickGremlin/download/) are currently triggering Windows Defender as Win32/Zpevdo.B Trojans.

![image](https://user-images.githubusercontent.com/44443959/50530841-c1f3d000-0acf-11e9-9525-572441629985.png)

**Comment by WhiteMagic** [comment]
Quite a few anti virus tools seem to be unhappy with Gremlin, or to be exact with PyInstaller as even a simple "Hello World" program triggers these AVs. I've submitted the joystick_gremlin.exe as a false positive to microsoft but I have no idea how long this will take / if they even act on this.

I tried seeing if windows defender would still be upset about Gremlin on my machine and it was not, though I'm unsure if it being the machine the release was developed on makes a difference or if my definitions were updated or any other possible combination of events.

Gremlin in the past was triggering AVs as well but after submitting the file as false positive this stopped over time, so I'm hoping this is the case this time around as well.

**Comment by mugenzaraki** [comment]
I had the same problem the first time I downloaded it but not since then each time I restart the pc the .exe disappears

**Comment by ventorvar** [comment]
Found a comment on SO that might help out? I'll try building using their method if I get a free moment.

https://stackoverflow.com/a/52054580

**Comment by mugenzaraki** [comment]
Thank you yes I have read but it doesn't help me any more than that, to be completely honest I don't understand a word of what he says

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Brian <notifications@github.com>
Envoyé : Saturday, December 29, 2018 5:03:17 PM
À : WhiteMagic/JoystickGremlin
Cc : mugenzaraki; Comment
Objet : Re: [WhiteMagic/JoystickGremlin] Current download detected by Windows Defender as a threat (#178)


Found a comment on SO that might help out? I'll try building using their method if I get a free moment.

https://stackoverflow.com/a/52054580

**Comment by WhiteMagic** [comment]
Yeah I might give this a go for the next version or if the next version suffers from similar issues. Though I did submit the current version of Gremlin to Microsoft and they should have removed it from their signature's database based on what I was told. No idea though how quickly that updates or how permanent / fool proof that is.

**Comment by mugenzaraki** [comment]
ok thank I'm going to wait.

**Comment by WhiteMagic** [comment]
R13 is still partially seen as the same issue that R12 was but hopefully none of the major AVs misdetect it. I may have to look into moving to 64bit version of python to get around this, since 64bit versions supposedly do not get detected in this manner.
