### ISSUE TITLE
Crash upon adding a remap on any Physical joystick.

### ISSUE THREAD

**Issue by danricho** [WhiteMagic/JoystickGremlin#18]
Using the following devices:
2 x T16000m
1 x Arduino Leonardo acting as standard joystick

When attempting to map a real control, when "Add" is clicked, the program crashes silently.

**Comment by danricho** [comment]
My apologies. Something was screwy with my vJoy installation. Fixed by reinstall.

**Comment by WhiteMagic** [comment]
Thanks for the report, good that you could figure out what was wrong. I'm going to add some logic in there that will actually tell the user that something is not right with vJoy for this type of scenario.

**Comment by danricho** [comment]
Hi again,

I'm wondering whether it is possible to map physical hat directions to virtual button presses?
I'm sure it is, i'm just not sure how.

Thanks for your great program!
Dan

**Comment by WhiteMagic** [comment]
I played around with that for the UI at some point in the past, but it got super ugly and confusing to use. The main issue is that hats only report when they get pushed into a new direction. As such there is only a "press" event but no "release" event for a hat direction.

For this reason I could easily expose all actions for hat directions since they simply trigger when the hat is pushed in that particular direction and there is no need for tracking the state. For buttons to properly work one has to track the state and emit the correct "release" event when a new hat direction is reported.

It is possible to implement and actually shouldn't be very complicated using the custom modules. There is already code for a finite state machine which can be used to track state and make sure the proper events are sent. It was mainly the UI side of things that was a nightmare (as usual). You can give that a go or if you're not exactly sure how to get started let me know and I should be able to put something together that does that fairly quickly.

**Comment by WhiteMagic** [comment]
Here is a modified version of your code that fixes the two issues you had.
https://gist.github.com/WhiteMagic/ec169727def8eb09b44fff84f93f1496

You'll have to add the second joystick and arduino back as well as modify the identifiers for your system since I removed that as I only have one t16000 here.

You were missing the vjoy parameter in the function name which through some python magic makes the vjoy instance available to the function. The other problem was the representation of the hat direction. Pretty much every library used inside Gremlin sadly uses some other weird encoding for them but the user facing one is based on Cartesian coordinates and allows encoding the directions of a 8-way POV hat.

A hat direction is a tuple with the (x, y) coordinates which can be either -1, 0, or 1. So left is (-1, 0), top right is (1, 1), center is (0, 0) etc.

There isn't really a log display window which could actually be handy when developing custom modules without actually having to setup the full source code and run it from within an IDE. At the moment there are two ways to at least get some form of feedback which are gremlin.util.display_error which shows an error message popup. The other option is standard python logging which is already setup inside Gremlin and goes to the logfile in %userprofile%/Joystick Gremlin/debug.txt. I've added a sample usage of both of these methods in the above code.

Hope this helps, if not let me know.

**Comment by danricho** [comment]
That is absolutely fantastic. Thanks so much!

I will trial it after work tonight.

**Comment by danricho** [comment]
Hello again Whitemagic,
I've got those working how I wanted. Its fantastic. I'm keeping them up do date in my repo.

I have another concept which required periodic running of a function and I think that the threading implementation I am trying isn't compatible.
https://gist.github.com/danricho/d94d69e39cf2ad68334c4d163271bb3f

Would you mind suggesting the best method for this type of script?

Cheers again,
Dan

**Comment by WhiteMagic** [comment]
Hey Dan that's good to hear.

I assume the goal of the script is to ensure SC sees your actual throttle setting is after dropping out of quantum travel or going coupling / decoupling?

Your version didn't quite work since the magic adding in of vjoy and joy only works for callbacks, i.e. the functions that get decorated with @tm1600m_left etc. And since you want that function to be called independently of any actual inputs adding them as the target for a timer or thread isn't easy if at all possible.

However, this ability to put joy or vjoy into the parameter list of a callback and having them assigned automatically is just convenience and as such you can grab the object that interface with vjoy or allow you to read the status of joysticks directly. That's what I'm doing in the first two lines of each of the functions.

The other issue was that you attempted to use an integer index with a vjoy axis (understandably) though vjoy has an internal enum that details the names of the 8 possible axis. The possible ones are: X, Y, Z, RX, RY, RZ, SL0 and SL1. I probably should add a bit of code into Gremlin that makes both cases work as one would expect.

I've modified your version to work with Gremlin you can find two possible ways of implementing it here
https://gist.github.com/WhiteMagic/b966f3e5a09e5605a06581249f2801b6

You probably will have to change the id used for the real joystick to what it is on your system, i.e. the system id reported by the Device Information screen.

One uses a timer that gets recreated every time as you did and the other one is a simple endless loop in a separate thread. They both have the same end result.

Let me know if this work or any other issues you run into. It's quite helpful to see the problems other people that don't know the code inside out run into.

**Comment by danricho** [comment]
I thought I would comment on the Gist rather than this bug report as it isn't really a bug report any more... Is that the best way to communicate with you?

**Comment by WhiteMagic** [comment]
Heh yeah not really a bug report but since github removed their messaging system it was the best option. Though you can also just send a mail to white.magic@gmx.de and we go from there.
