### ISSUE TITLE
Joystick input to keyboard input in (Python) module

### ISSUE THREAD

**Issue by RandieBarsteward** [WhiteMagic/JoystickGremlin#180]
Hi,
I currently have Joystick and Button box switches mapped to Keyboard inputs using Macro in the GUI but I would like to implement this within Python Modules so I can do more interesting things with states and conditions down the line.

What is the best way to have something like the below function execute a keyboard input instead?

` if event.is_pressed:
        vjoy[1].button(scmap.ShipLights).is_pressed = True`

So instead of calling the scmap module and looking up the ShipLights variable it just issues the keyboard input '3'? 

Sorry if this is a stupid question but I have been racking my brains about it for days.

**Comment by WhiteMagic** [comment]
To send a keyboard input you essentially have to create a macro. An example would be
```
# Create a macro that can be used repeatedly
key_macro = gremlin.macro.Macro()
key_macro.add_action(gremlin.macro.KeyAction(gremlin.macro.key_from_name("A"), True))
key_macro.add_action(gremlin.macro.PauseAction(0.1))
key_macro.add_action(gremlin.macro.KeyAction(gremlin.macro.key_from_name("A"), False))
```
This would be created outside the function called when your physical input is pressed, to avoid creating it over and over again. Then inside the function where you currently have the call to `scmap` you would add
```
if event.is_pressed:
    gremlin.macro.MacroManager().queue_macro(key_macro)
```
This would execute the macro, which in this case presses and releases the **A** key.

I grabbed the above example from this demo script I wrote a while back https://gist.github.com/WhiteMagic/3509b15e8f11f7af7846189f2380b3bd. The script itself won't work as is, due to the `JoystickDecorator` object having changed slightly in the way it's built, though given you have a working script you would have figured that out already I assume.

The two places where you can find info about the macro system and its usage is in the macro action plugin as well as the macro module. https://github.com/WhiteMagic/JoystickGremlin/blob/develop/action_plugins/macro/__init__.py and https://github.com/WhiteMagic/JoystickGremlin/blob/develop/gremlin/macro.py Technically everything the action plugins use is available to custom modules to use as well, it's just not very well documented, as I'm trying to figure out how to do this in the least terrible manner, as I have to fool the documentation tool into ignoring some imports etc.

Let me know if this helped or if you have other questions.

**Comment by RandieBarsteward** [comment]
Whitemagic,  that is fantastic!  

I have two questions, how does the macro deal with non standard keys (such as backspace and the Alt/Ctrl keys)?  

I have played with issuing multiple keys, is there a more elegant way than the below?

`# Create a macro that can be used repeatedly
key_macro = gremlin.macro.Macro()
key_macro.add_action(gremlin.macro.KeyAction(gremlin.macro.key_from_name("L ALT"), True))
key_macro.add_action(gremlin.macro.KeyAction(gremlin.macro.key_from_name("B"), True))
key_macro.add_action(gremlin.macro.PauseAction(0.1))
key_macro.add_action(gremlin.macro.KeyAction(gremlin.macro.key_from_name("A"), False))
key_macro.add_action(gremlin.macro.KeyAction(gremlin.macro.key_from_name("B"), False))`

**Comment by WhiteMagic** [comment]
No problem, if you have more questions feel free to ask.
