### ISSUE TITLE
'Save as' issue

### ISSUE THREAD

**Issue by fallout9** [WhiteMagic/JoystickGremlin#181]
Working in file A1.xml -> 'Save as' A2.xml -> Modify A2.xml -> 'Save' A2.xml -> Close JG -> Open JG -> It's supposed to open the last used file, but instead of opening on A2, it's opening on A1. Also, A2 it's not even in the 'Recent files', it has to be loaded.

**Comment by WhiteMagic** [comment]
This was just a quirk in how the "recent profile" was handled, it only cared about loading and not saving, though I've been having fun with reloading after saving for a while because of this behaviour. One of those things that takes 5 minutes to fix :-) done with f60040fd2909f98aa17948886df685173222e434
