### ISSUE TITLE
HID Guardian?

### ISSUE THREAD

**Issue by MedievalBunny** [WhiteMagic/JoystickGremlin#191]
I'm trying to get HID Guardian to work. 

I launch as admin, check the devices I want hidden, then unplug and plug again, but the devices are still visible. Tried a computer restart as well to no avail. 

Is there a step I'm missing? Another program I need to install? The HID Guardian link in the website FAQ is broken.

**Comment by WhiteMagic** [comment]
This utility https://www.autohotkey.com/boards/viewtopic.php?p=164497 is probably the simplest way to get HidGuardian installed. Without that the options in Gremlin won't have any effect, as they simply write registry settings (which is why admin mode is required) that HidGuardian reads for its own configuration.

I should fix the FAQ, as the links in the interface section of the documentation point to the right places.

**Comment by MedievalBunny** [comment]
That did it! 

That was, actually, a lot simpler than I was expecting.

**Comment by WhiteMagic** [comment]
That's good to hear :-) Typically that's the idea but at times things don't work out as easy as hoped or without issues.
