### ISSUE TITLE
Still failing to parse GUID in v13.1

### ISSUE THREAD

**Issue by GameOverture** [WhiteMagic/JoystickGremlin#207]
![joystickgremlinguiderror](https://user-images.githubusercontent.com/344924/56067443-2b2ee480-5d49-11e9-8b7b-9906aa857165.png)
![joystickgremlinguiderrorXML](https://user-images.githubusercontent.com/344924/56067449-2d913e80-5d49-11e9-8802-06ab6c44f4aa.png)

It seems my VPC MongoosT-50 Throttle is causing it problems.

**Comment by WhiteMagic** [comment]
If the profile was converted using the prior broken version then Gremlin won't fix that, because it doesn't really know how as I haven't written code to fix those profiles.

The simplest solution would be to revert to the R12 profile and have Gremlin reconvert it, as that should result in a XML file that has correct GUID values. You should have a `JoystickGremlinProfile.xml.v8` file in the same folder as this profile. If you remove the current `JoystickGremlinProfile.xml` and rename `JoystickGremlinProfile.xml.v8` to `JoystickGremlinProfile.xml` Gremlin will convert the profile anew.

**Comment by GameOverture** [comment]
That worked. Thanks!
