### ISSUE TITLE
Automatic profile switch does not correctly poll device state on load

### ISSUE THREAD

**Issue by Tahvohck** [WhiteMagic/JoystickGremlin#243]
When using the auto-profile-load feature, Gremlin does not correctly set the vJoy state based on physical device state. All axis are set to 50% and all buttons are set to False.

**Comment by WhiteMagic** [comment]
Polling physical devices, i.e. joysticks etc., is not technically possible as they are event based systems and Gremlin or any other program for that matter is only informed of state changes. Because of that Gremlin can't know what state a device is in when a profile activates.

Gremlin not being able to know the state of a device is only partially true though. While it's impossible to as a device to provide a list of axis, button, and hat states Gremlin can and does keep track of their last known state. Currently this is not or only partially used to set some things. The following issue, https://github.com/WhiteMagic/JoystickGremlin/issues/240, is aimed to address what you're running into as best as is possible within the constraints Gremlin operates in.
