### ISSUE TITLE
Profile binding to HW-ID

### ISSUE THREAD

**Issue by shimasteama** [WhiteMagic/JoystickGremlin#245]
Hi,
for helicopter simulation purposes with DCS I have a Hotas Joystick, a TM 16.000, Saitek rudders and two TM Throttles. Unfortunately Target does not support two throttles. I have already thought I wasted my money. But for Heli purposes it makes sense: one for collective, one for engine throttle. TM 16000 is used a a mission grip.
I found out that Joystick Gremlin (JG) would support both TM Throttles. After getting aquainted to JG I configured my setup. I also found out that in case the profiles of the two Throttles are mixed, I can - theoretically - swap. But... the swapping brings up also devices that are unique in the setup (by hardware type), and swapping is a matter of chance. After finally having configured my profile, and it takes some time, the last swapping just deleted the profile, I clicked on discard changes and all throttle configuration was gone. This was no fun ;-)
My suggestion:
JG detects what tab is for what (duplicate) hardware and binds this part of the profile to the hardware ID (which is eventually displayed in the tab). The user (nice to have) may also name the Tab for overview reasons. So instead of havin two times "TM Throttle" the Tab Title displays "Throttle Quadrant" and "Collective".
Is it possible to realize that with a next version? If so, I really would give JG another try. And in case you need some testing results, I would also be willing to give you bug reports if you want.
And: I really think JG is worth getting a product. Have you ever considered to sell a version with some little GUI refurbishment? I would buy it ....
Thanks
Harry

**Comment by WhiteMagic** [comment]
Based on some of the descriptions you give it sounds like you're using an older version of Gremlin, i.e. pre R13, as hardware IDs are no longer used. Due to that it's no longer possible that configurations between identical models of gear can be swapped, as Windows guarantees that the GUID assigned to each device remains unique to that device for as long as the Windows installation exists.

What you described with regards to detecting based on hardware id wasn't possible, as there is nothing that provides such a unique ID. Though Windows internally has such an ID which is what is used with R13 onward. The revamped swap tool actually displays that GUID, though it could benefit from showing the text provided in the device's description field which isn't done currently.

The next version of Gremlin will likely contain a UI overhaul due to internal changes which require changing the UI. As for small GUI changes, sadly anything that involves the term GUI is not small and always takes eons to do. I'd say 90% to 95% of my time spent on Gremlin is doing UI work.

As for selling a version of Gremlin, that's nothing I've ever considered, as at that point it becomes a job which not only means it's not longer something I work on when I enjoy it and have time but something where people have expectations etc. Let alone that the amount money made by selling it would stand in no comparison to the amount time and money I'd waste to handle taxes.
