### ISSUE TITLE
Can't pass through hat button from parent mode

### ISSUE THREAD

**Issue by TheJoeSchr** [WhiteMagic/JoystickGremlin#253]
Hi there,

I'm trying to set up a system where I can toggle through enemy/friendly targets via the hat button depending on the mode I'm in. That works.

But what I would also assumed would work (but doesn't) is that all the other buttons of the hat get "passed" through. Like it does for "normal" buttons. But instead if I press a hat button that is not mapped in my child mode, nothing happens?

Am I doing something wrong? Is this not supported?

Thanks a lot!

**Comment by WhiteMagic** [comment]
You are not doing anything wrong as the inheritance system doesn't work when a physical input has actions defined in a child mode. Because you specify actions on the hat in your child mode, anything that the parent mode had associated with the hat will no longer be executed. Running of actions defined in a parent mode only happens when a corresponding child input has no actions specified.

There also isn't any way around this in the current version of Gremlin. The things I currently work on with a library of specified actions should make this less of an issue as you could reuse the same actions in both modes, though you would still have to add them to each mode.

**Comment by TheJoeSchr** [comment]
Ok, thanks! Looking forward to the new release! Thanks for all your great work!
