### ISSUE TITLE
Figuring out how to manage a toggle switch

### ISSUE THREAD

**Issue by Longwing** [WhiteMagic/JoystickGremlin#286]
I've been poking around the internet and various forums for days, and I can't seem to sort out the answer to my problem.

I have a button box with switches on it. I want to create a set of macros so that a switch triggers a vJoy button on press, and the same vJoy button on release (for games that don't support switches and expect a button input for on, and the same button input for off). 

No matter how I set the conditions on the macros, it works on press but doesn't work on release. Here's my latest variant. Nothing I do seems to work:

![image](https://user-images.githubusercontent.com/9980334/78624381-73e38580-7857-11ea-80b5-a7e8b8f64bf8.png)

![image](https://user-images.githubusercontent.com/9980334/78619743-30374e80-784c-11ea-9f6e-a7d771e3b2e4.png)

Any idea what I'm missing? I just can't seem to get it to parse on release.

Many thanks,
Daniel

**Comment by Longwing** [comment]
To be clear, I've tried far more logical setups first, the result is the same, it works for pressing the button, but not for releasing it.

![image](https://user-images.githubusercontent.com/9980334/78624288-45fe4100-7857-11ea-991a-e5b2104913e6.png)

**Comment by Longwing** [comment]
After much experimentation, I was able to finally get the result I was looking for. I needed to rebind the button to a virtual button first, then key my actions from the virtual button instead of the actual device button.

I'm happy to have it working, but I'm also confused. If Joystick Gremlin cannot read the release action of a physical button, why is it even an option?

**Comment by WhiteMagic** [comment]
If you use the action condition with pressed and released as opposed to the joystick condition you show in your previous image then it should work. That the joystick condition with release is not working is a bug that I never ran into, due to me never using a joystick condition matching the physical input.

The reason there are joystick, keyboard, and action conditions is that the action condition is there to make it simple to check if a button (or a virtual button like hat direction or axis range) is pressed or released. The joystick and keyboard condition were always intended to conditionally prevent or enable the execution of an action based on the state of some other input. Due to this, I've never actually tried the setup you show. Though you're not the only one doing this and running into problems with it.

Theoretically using the joystick condition should work but I suspect that the joystick state does not get updated until after the action attempts to execute, so as far as the action goes it still thinks you haven't released the physical input. If that was reordered then it would work.

Having a setup like this https://imgur.com/KgKHeNd should work though.

**Comment by Longwing** [comment]
Thanks. After some additional experimentation I was able to finally get it working using a template very similar to the one you just demonstrated.

![image](https://user-images.githubusercontent.com/9980334/78663847-de6ce380-78a0-11ea-8918-cefd2cac29ec.png)

![image](https://user-images.githubusercontent.com/9980334/78663875-ea58a580-78a0-11ea-9bd2-4fefc3e0faad.png)

Personally, what tripped me up was the wording of the action condition. Every time I tried to get this working I'd see "activate when this (virtual) button is..." and think "Well that doesn't apply here because I'm dealing with the physical button, not a virtual one." Once I got past that mental block the rest of it was pretty simple.
