### ISSUE TITLE
Identifying t.16000M FCS left/right mode

### ISSUE THREAD

**Issue by dixonte** [WhiteMagic/JoystickGremlin#294]
I've done some basic investigation into how one might programmatically identify if a given t.16000M stick is in left-hand or right-hand mode. I've been able to identify a single bit in a HID trace that differentiates the two, but I'm unsure where to go from there.

Ideally I'd like to make a plugin since this is specific to a single device type, but it doesn't look like a suitable hook currently exists. Even if it did, by definition of my goal I need to be able to open a channel to a specific HID device, where both have the same VID and PID.

Do you have any ideas?

**Comment by WhiteMagic** [comment]
Gremlin at the lowest level deals with DirectInput, and even that I have segregated away into its own separate library, so to Gremlin there are only notifications about "this device input now is in this state". As such Gremlin has no notion of low-level input handling, by design. 

What exactly would you want the plugin to do exactly? The only plugins, so to speak, Gremlin supports are actions and containers. Extending or modifying core parts of Gremlin is not possible in that manner. If the idea is to simply rename the devices such that they are easier to tell apart then that would be more suited to DILL. Even though the library doesn't deal with HID that library might be amenable to handle this, but Gremlin should not delve into low level hardware details as that removes the very simple event based data stream it's relying on.

**Comment by dixonte** [comment]
Ahh, I'm blind. You're right, it'd be a much better fit there. I'll go look at the DILL project later.
