### ISSUE TITLE
TWCS Throttle only showing 1 hat

### ISSUE THREAD

**Issue by dragonmaus** [WhiteMagic/JoystickGremlin#295]
I am trying to create a basic configuration combining my T.16000M + TWCS Throttle HoTaS setup, but am having trouble mapping Hat 2 and Hat 3 on the throttle. They are registering as 4 buttons each, instead of proper hats, and I cannot select any of the vJoy hats as the Remap target.

Expected behaviour: TWCS Throttle has 3 hats in `Device Information`

Actual behaviour: TWCS Throttle has 1 hat in `Device Information`

**Comment by WhiteMagic** [comment]
How is Windows (via joy.cpl) showing the inputs? The reason is that Gremlin should be showing the same information and based on the description of the TWCS it is entirely possible that the 2 4-way hats are actually implemented as buttons. I don't have a TWCS so I can't double check what the correct behaviour is.

**Comment by dragonmaus** [comment]
Hrm, yeah. It appears that they are implemented as buttons (as seen [here](https://i.imgur.com/mPl9uKV.png)).

Is there any way to map a set of buttons to a hat?

**Comment by WhiteMagic** [comment]
Technically you can use the macro function to achieve this, however, it is quite tedious due to having to use conditions and getting into possibly weird states when you press multiple directions. A while ago I wrote this plugin https://gist.github.com/WhiteMagic/3790007670078cf2fadaf7eeb6f2a113 which allows you to specify a vJoy hat and the buttons that map onto it.

To use it add it via the Plugins tab. Clicking on the "+" icon will add another instance such that you have one for each hat. The "cog" symbol will allow you to configure the individual instances as needed.

**Comment by dragonmaus** [comment]
I'll use that, thank you for the assistance.
