### ISSUE TITLE
FR: Allow an initialization function in user plugins, or a way to change or clear a user plugin periodic event

### ISSUE THREAD

**Issue by IslandJohn** [WhiteMagic/JoystickGremlin#316]
I'm writing some user plugins for which I'm using periodic events to initialize state based on current joy/vjoy state. I can't stop the registry afterward since it's globally shared. It would be useful to either allow a plugin's period to return True/False or some change in periodicity to adjust its behavior, or to provide an initialization API that has access to joy/vjoy.

I can get access to joy and vjoy directly (e.g. gremlin.input_devices.JoystickPlugin.joystick) at module load time, but this leads to failures if the plugin is not yet configured (e.g. when configuring). Is there a way to determine whether a plugin is being loaded during config or actual execution?

**Comment by WhiteMagic** [comment]
Interacting with the periodic registry when Gremlin is running is not something it was ever designed to do. The registry is populated when Gremlin is activated and then is executing whatever it contains until Gremlin stops. Anything that wants to dynamically start/stop periodic callbacks while Gremlin is running is not doable with that system as it stands.

I'm also not clear as to why you want to use a function that's constantly being run to perform initialization of states, as that seems kind of a hackish way to solve the actual problem. Also to access vJoy and joystick data you should not be using the plugins classes but rather the actual interfaces, i.e. `input_devices.JoystickProxy` and `joystick_handling.VJoyProxy` which are the things the plugins effectively expose.

As for knowing whether or not a plugin is loaded during configuration or execution, the `_get_identifier` method in a variable might provide some information, i.e. whether or not `None` or actual data is returned. From memory and looking at the code the `CodeRunner` class, which actually executes a profile, inserts the identifier information when the plugin instance is loaded/executed. This doesn't happen when the plugin is configured and I think this is the way I handled differentiating between configuration and execution time. However, there might some aspects I'm not thinking of as the entire user plugin system uses serious black magic and I have forotten half of the things that were needed to make it work.

**Comment by IslandJohn** [comment]
Thanks... since I didn't see a clear path to initialization, I first used the period function, agreed with you, as a hack , until I realized the registry was global. Thanks for the pointed on using the proxy, I'll switch to that. Currently, variables' value is None during configuration, so I'm using that, although "Mode" seems to always be set, so I have to use something else I define in the plugin. I'll take a look at _get_identifier.

Have you thought of allowing the period function to modify either the time, or have itself removed through a return? Or providing some init method for both configuration and running?

**Comment by WhiteMagic** [comment]
The way the periodic registry is used did never intend a runtime interaction, as it is only used with the periodic decorator. Technically Gremlin already contains a scheduler to which actions are added and removed at runtime in the macro manager. Though the obvious restriction there is that it is only handling macro actions and nothing else. If I was to add support for runtime periodic functions then it most likely would be by generalizing that scheduler as it already contains most of the needed functionality.

Though realistically for your particular problem the correct solution are other events on which functions can be triggered. This is what #140 is about. Such events would include, mode switches, activation/deactivation of Gremlin, etc. Overall those events are most likely more useful than being able to add/remove periodic callbacks at runtime. This is mainly because implementing this in a plugin is doable while getting to know about the other events is actually impossible.

**Comment by IslandJohn** [comment]
#140 looks like the place for an config/run event. Thanks. I'll use testing for a variable value a None for now to differentiate between config and run.
