### ISSUE TITLE
Loading a profile onto a fresh install fails to load any settings

### ISSUE THREAD

**Issue by BGG-DIP** [WhiteMagic/JoystickGremlin#402]
Hello, I recently built a new system (entirely new install) and copied Gremlin and all of its dependencies over via USB. However, I try to load the profile xml and everything remains unlinked and blank other than the names of a few custom modes, both of which are also blank when selected. I have also tried removing the copied Gremlin files, rebooting, and reinstalling Gremlin's .msi from the website - no success here either. vJoy is installed and configured the same way as the old system, and the sim hardware is unchanged. Is there something I'm missing here?

**Comment by WhiteMagic** [comment]
This is the expected behaviour, as a new system means your device GUIDs have changed, which is what Gremlin uses to identify them. You can use the Actions -> Swap Devices tool to reassign the physical devices to the old ones in the configuration. One thing to be aware of though is that if you had descriptions on the actions they are currently being lost. This can be worked around by manually replacing the GUIDs in the XML profile, but unless you're comfortable with that carries a risk of mangling things up.
