### ISSUE TITLE
Is there a way to reset a chain other than the timeout?

### ISSUE THREAD

**Issue by MockbaTheBorg** [WhiteMagic/JoystickGremlin#452]
Hi there,

This is not a real issue, but more like a question or feature request:
Let's say I have a button to switch "View to cockpit", basic map-to-keyboard action which presses F1.
Then another button is a chain of multiple "External views", which go trough F2, F3, F4, F5, F6 and so on on each press.
When I press "View to cockpit" after going through, let's say, external view F4, it works fine, goes back to cockpit as expected.
However when I press "External View" it continues from F5. I would like it to be reset to F2, the top of the chain.
The timeout kinda works but if I take too long to switch between external views, then it resets back to F2, even though I am still browsing through external views.
It would be better if the chain could be reset by the pressing of any other button than the one which has the chain.
Maybe this is already possible, but I couldn't find yet a way to do it.

Thanks!

**Comment by WhiteMagic** [comment]
As mentioned on discord, this is not possible and likely not something that will ever be supported directly via the UI. The reason is that containers are supposed to be independent of each other. Anything that needs this level of inter-connectivity between actions moves towards custom plugins.

While it's technically possible to code such features, doing so in a generic way would add significant complexity and overhead for limited use cases. Furthermore, it would have significant knock on effects on the UI, likely making it even clunkier and confusing to use and code for.
