### ISSUE TITLE
Feature request: Axis to buttons with relative movement triggering actions

### ISSUE THREAD

**Issue by morgangrubb** [WhiteMagic/JoystickGremlin#456]
What I mean by this:

* If the axis moves in a positive direction 2% of the range then trigger button 1 _once_
* If the axis moves in a negative direction 2% of the range then trigger button 2 _once_

This is specifically to work around the fact that MSFS doesn't have trim axes for roll and yaw (but does for pitch, go figure) and instead accepts button presses in either direction.

This is the axis to button configuration I have at the moment:
![convert trim axis to buttons xml - Joystick Gremlin 2022-10-12 6_22_22 PM](https://user-images.githubusercontent.com/195705/195477166-458fa80a-bcc3-47ac-984c-0622889c0096.png)

This configuration results in a fairly large deadzone and overeager mashing of the buttons once the axis enters the activation zone which is defined in absolute terms. 

I apologise if this is already possible and I just haven't been able to figure it out.

Cheers

**Comment by WhiteMagic** [comment]
This is an unlikely kind of condition to be added, at least not any time soon. The reason is that all conditions in Gremlin are unaware of history, i.e. they get a singular input and react to it. It likely isn't breaking the current or future interface for conditions, so it likely would be implementable without redoing things touching it. Though it is not something that would be a high priority. The main reason is that using user plugins this is already solvable, for example, https://gist.github.com/WhiteMagic/ff636574b45a12480fd0bd6f1a92740e will send vjoy button presses based on relative axis changes.

**Comment by morgangrubb** [comment]
That looks like it will do the job quite well. Thanks!
