### ISSUE TITLE
Spacemouse Pro not centering

### ISSUE THREAD

**Issue by mrjester888** [WhiteMagic/JoystickGremlin#51]
I have a 3D Connexion SpaceMouse Pro that is behaving like a mouse instead of a joystick.  Also, input values wrap at the edge.  Physically, the device recenters itself and behaves like a joystick.

When the spacemount is used with Sx2vJoy, the behavior is correct.

**Comment by WhiteMagic** [comment]
Yeah the data the space mouse provides when seen as a joystick is rather odd. It essentially continuously sends a deflection value which accumulates and at some point wraps around. A while back someone else had the same issue and the following script made it work for his purposes.

https://gist.github.com/WhiteMagic/488ac6bc2de02706d13a219d52e89b99
If you are a backer of Star Citizen you can see the discussion surrounding this here https://forums.robertsspaceindustries.com/discussion/comment/7328439/#Comment_7328439 it's a bunch of posts before and after.

You most likely will have to change the value in line 6 to what Gremlin shows for you device using the Tools -> Device Information screen. This also assumes that the increments sent by the space mouse are relatively small (0.1) per tick which I'm not sure if this is consistent across devices.

The Sx2vJoy does read the actual USB data directly from what I can tell while Gremlin uses a different library to get this information. Due to not owning a space mouse I've never looked into what the difference in the reported values is and if there would be a better way to obtain absolute values.

**Comment by WhiteMagic** [comment]
Closing for now, if the issue persists or there's more information feel free to reopen this.
