### ISSUE TITLE
Where to get help and guidelines about using Joystick Gremlin

### ISSUE THREAD

**Issue by DanTDBV** [WhiteMagic/JoystickGremlin#52]
I have been looking around for a place to learn more about how to use JG and ask questions about it.

The only place I have been able to find is this thread on RSI:
https://forums.robertsspaceindustries.com/discussion/237458/joystick-gremlin-joystick-configuration-tool
But it is blocked unless you buy a Star Citizen module. 

The other threads that I have found around have not had any help in them.

JG sounds like a very promising and usefull tool, but without access to some help it will be hampered.

I mention this because I can see the potential and wish to spread it to a bigger audience.

To my issue.
I am stuck at the first step as nothing happens when I create a new profile.

I run both vJoy and JG as administrator in windows 8.1 Danish. 

What information do you need from me to id the problem?

Respectfully yours

Dan from Denmark

**Comment by WhiteMagic** [comment]
The link is to the old, now archived, forum the new thread on the replacement system is here https://robertsspaceindustries.com/spectrum/community/SC/forum/50174/thread/joystick-gremlin-joystick-configuration-tool though I suspect that you still would have backed the game to be able to post there. Though sending private messages through that should work and is how in the past I've stayed in contact with people that didn't back the game but were interested in Gremlin.

And yeah I might have to look into getting some form of forum / discussion thing so it's easier for people that are not backers to get in contact. Historically it's just been over there simply because Star Citizen was the reason I started writing this and haven't played flight sims in ages.

As for your problem what exactly do you mean with "nothing happens"? When you launch Gremlin it should show a tab for each of your joystick devices which you then can assign actions to, such as mapping physical axis to virtual ones etc. Creating a new profile should essentially just present you with a clean slate with not actions assigned to any of the inputs but nothing else would happen.

I've recorded a quick demo of how you'd bind a remap action from a physical button to a virtual one. The way the UI looks at the beginning  of the video is what it will look like when first started, obviously with different device tabs.
https://www.dropbox.com/s/br9mfz193ln3a3m/jg_example.mp4?dl=0

Maybe this clarifies a few things and otherwise either reply back here or send me a PM via spectrum both should work fine.

**Comment by DanTDBV** [comment]
Thank you for the reply and video Whitemagic and welcome to reddit.

I have been to busy to do much on the pc, so that is the reason for the latenes of my reply.

I now understand how it should work. I still have problems, but I think it would be better to start a thread about it on reddit HOTAS. 

I am going to close this as I now know where to find help.

For the rest of you.
You can get help for Joystick Gremlin here:

Support thread on RSI. You have to be a SC backer to reply in the thread but you can PM Whitemagic there, with a free account.
https://robertsspaceindustries.com/spectrum/community/SC/forum/50174/thread/joystick-gremlin-joystick-configuration-tool

reddit HOTAS forum:
https://www.reddit.com/r/hotas/
