### ISSUE TITLE
Input Highlighter Not Switching Devices 

### ISSUE THREAD

**Issue by Wolfereign** [WhiteMagic/JoystickGremlin#75]
I'm not sure if this is a bug, limitation, or on purpose. 

Basically if i'm in the tab for one device and press the button on another device the interface doesn't switch tabs/devices and highlight the pressed button. 

Highlighting works for buttons if you're already in the tab for that device but not if you're in a different tab.

This could also be extended to changing modes to highlight a button pressed in that mode. Though that would require the interface to recognize mode switch buttons even when not running.

**Comment by WhiteMagic** [comment]
Yeah that behaviour your seeing is intended, though that is not to say this couldn't be changed by giving users options. At the moment the design is that Gremlin only ever highlights inputs of the currently selected device and never does any such thing when it's active. One reason is that I didn't want people to lose some action setups they're doing because they accidentally bumped one of their other devices. This was partially due to a flawed "has this axis moved enough" detection logic.

The mode based stuff would require that Gremlin is active for this to work. This might be interesting if I ever add automatic reloading of changes for an active profile. At the moment for any change to work Gremlin has to be stopped and reactivated. If this was not the case having the ability to jump quickly to a particular action to tune it might be quite handy.

**Comment by Wolfereign** [comment]
I could see wanting the behaviour to work both ways.  You can close this or add it as a feature request for a user defined option.

**Comment by jarpy** [comment]
I actually have no highlight response at all, even on the correct tab.

**Comment by WhiteMagic** [comment]
No worries, as long as things are working I'm happy. Or if it's a bug I'm happy to know about it so I can squish it :-)

**Comment by jarpy** [comment]
It was a bug… in my USB controller. The absence of light from the LEDs on my joystick interface probably should have tipped me off. :)

Loving version 9. It's beautiful. 💚

**Comment by WhiteMagic** [comment]
Option added which allows enabling device tab switching on input (41ed61e221e4149d99e140e6cb111f9675a8fdbb)
