### ISSUE TITLE
How to execute an action on release

### ISSUE THREAD

**Issue by Carlton2001** [WhiteMagic/JoystickGremlin#76]
Hi,

I don't understand how to execute a Map to Keyboard on button release.
I'm on R9.1 and conduct my tests with a T.16000M prior to apply my learnings to a Warthog.

I have one vJoy Device and I map my T.16000M on this vDevice using the "Create 1:1 Mapping"
Everything works fine if I just Add a container to my input without doing anything more.
For example I simply execute "T" with Button 2. I works fine (when button is pressed)
![capture1](https://user-images.githubusercontent.com/4473116/34326811-13a06482-e8b6-11e7-8035-2d5b5a58f77b.JPG)

But I can't understand how to execute "T" on Button 2 released.
![capture2](https://user-images.githubusercontent.com/4473116/34326813-1b6ed5f4-e8b6-11e7-97f4-eddcab45f936.JPG)

**Comment by WhiteMagic** [comment]
The reason this isn't working is the way both Remap and Map to Keyboard work. Their job is to mimic your input on one physical input, say T16000 Button 2, on another virtual one, e.g. vJoy 1 Button 2 or Keyboard key T. That means press and hold a virtual input as long as you press and hold the corresponding physical one. As such Gremlin interprets your setup as "Only forward my input when Button 2 is released". As this corresponds to "Releasing key T" you won't ever see anything happening.

To get the result you want which is to "tap T when I let go of Button 2 on the T16000" you have to use a macro that has press and release for T. With regards to the condition you're using, being specific and selecting the input directly, i.e. T16000 Button 2, works you could also just use the "Action" condition which always refers to the physical input with with the actions are associated.

Put together this looks as follows:
![macro](https://user-images.githubusercontent.com/5612/34329273-ba4696ec-e8f9-11e7-8abf-db3f9482200d.png)

**Comment by Carlton2001** [comment]
Thanks for your quick response, I'll try that.
Happy Holidays to you.

**Comment by Carlton2001** [comment]
Ok it works, I had a hard time to figure that you must select the condition Action. Did you see that after a save, the condition is always reset to "Keyboard" on the GUI ? Even if you selected "Joystick" or "Action".

Thanks !

**Comment by WhiteMagic** [comment]
Yeah that's related to UI stuff, the way I'm doing all the UI work isn't super atrocious but also not exactly really good. As a side effect some state information and user selections aren't retained when updates to the UI are made.

Typically the UI is refreshing itself when a change is made in one part that has an effect somewhere else which isn't really the case here so I'll have to look into that. Technically I shouldn't have to ever refresh anything manually if I were using all the proper UI techniques but I don't since they tend to result in me having headaches. So I end up with an in between system that typically works well enough and lets me keep my sanity when working with UI stuff.

**Comment by WhiteMagic** [comment]
This should now work in R10.

**Comment by stormrider123** [comment]
It doesn''t work.

**Comment by stormrider123** [comment]
![image](https://user-images.githubusercontent.com/45309507/216279786-e598697b-e3c4-4da0-9e5b-b9923c1dff44.png)
![image](https://user-images.githubusercontent.com/45309507/216279863-69cc66d2-caa1-44ce-9ba1-30f6e5136708.png)
