### ISSUE TITLE
sx2vjoy integration or ability to remap vjoy devices.

### ISSUE THREAD

**Issue by Req-Beard** [WhiteMagic/JoystickGremlin#77]
Hello, your software is amazing but unfortunately I and other space mouse users cant really use it. Due to shoddy drivers by 3dconnexion (maker of space mouse) sx2vjoy was created to make it possible to use the space mouse in full 10bit mode (driver nukes it to 8bit and ruins the deflection values).  Its method is feeding usable data to a vjoy device and makes it function properly. 

Would it be possible to merge the code so if it sees the proper hardware ID it loads the same values as sx2vjoy? If not when do we expect joystickgremlin to be able to read vjoy devices?

https://github.com/Lasse-B/Sx2vJoy

Thanks a bunch!

**Comment by WhiteMagic** [comment]
From what I remember when I looked last a sx2vjoy was that it directly read usb hid data which Gremlin doesn't do. So while technically it could be done it would only make sense if I moved all input reading to go this low level which at this time isn't very likely as it's quite a bit of work which wouldn't improved things for joystick etc. inputs.

So the more sensible solution is to allow remapping of vJoy devices. Gremlin can already read them but actively discards them as a "physical" input which they aren't. Though there are case such as sx2vjoy where having the ability to treat such a virtual device like a physical one (there is no difference as far as incoming data is concerned). 

This is mostly a UI question as it would not take very long to have the current UI treat vJoy devices the same as the physical ones. The bit that will take me time is figuring out a good way to let those users that need this feature enable / configure it without confusing those that don't need it with a tab where you can map vJoy "outputs" as if they were "inputs".

The other thing I don't know is if Gremlin and vJoy can work together. From Gremlin's side it should be ok as it only grabs and maintains hold of vJoy devices it actively uses to output to. If sx2vjoy behaves in a similar manner they should be able to work side by side.

**Comment by Req-Beard** [comment]
I can understand the concern regarding design language and confusing the user. What if you had a advanced menu and a check box that says something like *3dconnexion compatibility mode (read vjoy). Hopefully regular users are scared away by it while being clear to space mouse users what it does.

**Comment by WhiteMagic** [comment]
Yeah it's probably going to be some type of option that is disabled by default which allows you to pick which vJoy devices you'd like to treat as a source of events to react to. This is actually not restricted to just sx2vjoy, there's another case where someone could have used that ability and it's been on my list of things to do ever since (https://github.com/WhiteMagic/JoystickGremlin/issues/53) ... just a day sadly doesn't have anywhere near enough hours in it :-)

**Comment by WhiteMagic** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Allow vJoy devices to be used as input devices](https://trello.com/c/eDsYDfml/8-allow-vjoy-devices-to-be-used-as-input-devices)

**Comment by andreaspada** [comment]
That's for sure will be a killer feature! I'm purchasing a spacemouse, but I used my trackball with a custom FreePIE script by at least an year and a half, and I always wanted to be able to use Gremlin advanced GUI and conditional tools to work aside. I mainly use FreePIE to map my trackball as a bunch of virtual axis but, as I cannot pass the vJoy output to any other program as input, I have to code also all the curves and conditions. If we could be able to use virtual devices as input, that's will be amazing!

**Comment by WhiteMagic** [comment]
Good news is that I've implemented this now. Still have to properly test it and see if I forgot some odd corner cases that break stuff horribly. But the next release should contain the option to pick vJoy devices as "physical inputs" which will make Gremlin ignore them as a virtual device but instead read the vJoy device's data as if it was a real device.

**Comment by andreaspada** [comment]
Awesome!!! That's fantastic!!!

**Comment by andreaspada** [comment]
Can you share an experimental build to let us test and help in debug?

**Comment by WhiteMagic** [comment]
Building one shouldn't be hard, I mainly have to double check a few things first so that it doesn't just crash randomly from other things :-)

**Comment by WhiteMagic** [comment]
Ok finally got around to doing the bare minimum checks and built a new version which you can grab here
https://github.com/WhiteMagic/JoystickGremlin/releases/tag/Release_11_pre1

If you have a profile that loads a custom modules that won't work anymore since I haven't implemented the profile conversion stuff for R11 yet. Changing whether or not a vJoy device is an input or output is done via the Settings tab, so you can change those settings on a per profile basis.

Gremlin should not attempt to grab access to vJoy devices that are set to be inputs, however, if another application grabs a vJoy device Gremlin considers as output, ideally Gremlin should just ignore said device but I haven't tested all possible combinations of those situations.

**Comment by WhiteMagic** [comment]
This should now be feasibly with R11 by defining the vJoy device used by sx2vjoy as an input. There will be issues if other programs grab a hold of all vJoy devices as opposed to just the one they write to.

If there are issues with the vJoy as input feature please create new issues.
