### ISSUE TITLE
Redirect Axis error 

### ISSUE THREAD

**Issue by Francky63** [WhiteMagic/JoystickGremlin#78]
I have created a profile to remap the TH TQS Throttle with tusba 2  -  range knob axis 3 on vJoy Dial/Slider2 axis 8.
This remap is conditioned from the Cougar S3 pressed.
(there is also PULSE py script implemented for other button on TQS).

This is because i want to use it also as a zoom or FOV in Falcon BMS.

i used BASIC, REMAP action and condition EXECUTE IF ALL.

Very often (but not always) i get this error as soon as i try to use it inside Falcon (last line I guess is enough):

File "gremlin\input_device.py", line 359, in __getitem__ gremlin.error.GremlinError: 'No device with the provided identifier: 6 exists'

**Comment by WhiteMagic** [comment]
The error essentially says that am attempt is made to access a non existent device. In this instance that would be the device with id 6 as assigned by windows. Without the other lines I can't say from where the attempt at accessing this device is made.

This could happen if windows changes ids or a device is disconnected intermittently. Another source could be the custom script that may contain a no longer valid id.

**Comment by Francky63** [comment]
The axis is randomic sometime 6 sometimes 4 … in my script there is not axis interaction. Attached you can find my JG directory with the scripts conf and log reporting the errors.

 

Regards

 

Franco

                                 

Da: WhiteMagic [mailto:notifications@github.com] 
Inviato: giovedì 18 gennaio 2018 01:31
A: WhiteMagic/JoystickGremlin <JoystickGremlin@noreply.github.com>
Cc: Francky63 <franco@dallera.eu>; Author <author@noreply.github.com>
Oggetto: Re: [WhiteMagic/JoystickGremlin] Redirect Axis error (#78)

 

The error essentially says that am attempt is made to access a non existent device. In this instance that would be the device with id 6 as assigned by windows. Without the other lines I can't say from where the attempt at accessing this device is made.

This could happen if windows changes ids or a device is disconnected intermittently. Another source could be the custom script that may contain a no longer valid id.

**Comment by WhiteMagic** [comment]
It seems that github stripped the attachment out, could you upload the files to dropbox, google drive, or similar?

**Comment by Francky63** [comment]
Sorry for the delay,

here is a google drive link:

https://drive.google.com/file/d/15RbBJ7vDFxbrVW1IaTQi-AOHJPxMtfOh/view?usp=sharing

 

let me know if you are be able to get it

 

regards

 

Franco

 

 

Da: WhiteMagic [mailto:notifications@github.com] 
Inviato: venerdì 19 gennaio 2018 00:34
A: WhiteMagic/JoystickGremlin <JoystickGremlin@noreply.github.com>
Cc: Francky63 <franco@dallera.eu>; Author <author@noreply.github.com>
Oggetto: Re: [WhiteMagic/JoystickGremlin] Redirect Axis error (#78)

 

It seems that github stripped the attachment out, could you upload the files to dropbox, google drive, or similar?

**Comment by WhiteMagic** [comment]
Ok looking through the configs and the errors there are two causes for the error you're getting. The first one which is complaining about the device with windows id 6 is caused by this line in the cougar.xml

`<condition comparison="pressed" device_id="72287232" device_name="Thrustmaster HOTAS Cougar" id="3" input="button" windows_id="6"/>`

That condition makes Gremlin attempt to grab the windows device with number 6 which normally doesn't exist on your system. However, it came into existence when you got the error with device with windows id 4 missing.

At some point it looks like somehow devices got either unplugged and re-plugged or windows after some power saving stuff re-detected devices and assigned them new ids. At the time that this happened your Cougar used to be on windows id 4 but due to that re-plugging stuff was assigned id 6. This then caused the error at that time but also resulted in the id on this condition to be remembered as 6 rather then 4 (which is the usual id for your cougar it appears). The easiest way to fix this is to redo the condition by reselecting the input you want the condition to trigger on, i.e. button 3 on the cougar. That will re-record the device information and thus saving to correct ID. That should fix the problems but if the windows id change it will throw an error again.

The conditions using the windows id for the checks is actually bad and I'm not sure why I made Gremlin use those in this instance. For setups like yours where all the USB based device ids are unique I don't need to rely on windows assigned ids. So I'll have to look into that and figure out if this is just an oversight or if I had some sensible reason for doing it this way.

**Comment by Francky63** [comment]
i deleted the configuration and made it again and it works for a while ... now i get another error like if vJoy is not configured but vJoy is in the windows joystick device list... 
with this error i'm not be able to open Gremlin UI interface and i have to kill it from task manager.

I added  a Pokeys virtual joystick but also if i disconnect it the behaviour is the same also it i delete gremlin configuration directory

here the log and configuration files

[](https://drive.google.com/file/d/1jesnDAhxtJU7yAVl4EVdoA6k15bFS7o0/view?usp=sharing)

**Comment by Francky63** [comment]
Sorry, after more tests it look like if it is in conflict with POKEYS virtual joystick

**Comment by Francky63** [comment]
now also without POKEYS i'm not be able to open joystick gremlin ithe error is that vJoy isnot enable but it's running and enabled

**Comment by Francky63** [comment]
I closed it by mistake ... i try to recreate my config but i still have the same error i'm not more able to use JG
