### ISSUE TITLE
Failed setting axis value

### ISSUE THREAD

**Issue by stephengeorgewest** [WhiteMagic/JoystickGremlin#90]
Version Release 9.2

Windows 7

I seem to get this error after I leave the profile activated then leave, then windows goes to sleep, then wakes up again.

![error](https://user-images.githubusercontent.com/1442484/36558484-7243d2d0-17c8-11e8-9e2e-623833c167e4.png)

It seems to repeat quite a bit.

![errors](https://user-images.githubusercontent.com/1442484/36558546-949a4a8a-17c8-11e8-8496-7c97fae1abaf.png)

Here is the log, do you need anything else?
[system.log](https://github.com/WhiteMagic/JoystickGremlin/files/1749184/system.log)

**Comment by WhiteMagic** [comment]
I'm not exactly sure what happens as sadly my error message I'm emitting is a bit sparse on details, i.e. I don't actually say which device, axis and value it tried using ... which is something I should fix.

My best guess is that upon waking up the physical devices become active before vjoy is functional again and that for some reason a chunk of axis values are sent which then throw errors since the vjoy device is not there yet. Another possibility could be that Gremlin actually no longer holds the vJoy device after wakeup but still thinks it does. I'll have to see if I can reproduce this in a VM as otherwise debugging this will be painful.

The reason you're getting spammed by the exceptions is I think that the systems generates a ton of joystick events which are all processed at once, each one resulting in an exception until Gremlin deactivates itself from the first exception. But that doesn't happen before a whole bunch of other exceptions were thrown. Sadly I don't think there's an easy way around this.

I'm not sure if I can detect windows going to sleep / waking up in order to automatically disable and re-enable Gremlin based on those events.

**Comment by WhiteMagic** [comment]
It appears that this issue is linked to the same underlying bug that was addressed when fixing  #129. So the next release should no longer cause this error when the machine is waking up and a profile is actively trying to send data to a not yet or no longer owned vJoy device.
