### ISSUE TITLE
Vtual Button - Automatic Key Release

### ISSUE THREAD

**Issue by peterbeste** [WhiteMagic/JoystickGremlin#97]
Hello,

I am trying to set up a joystick axis as a combined throttle/break in the Game Train Sim World.
The Game works this way:
- Each A-key-press pushes the throttle forward = increases the acceleration by one notch
- Each D-key-press moves the throttle backwards = decreases the acceleration by one notch

I tried the following:
- created a basic container to line the vjoy-axis to the Joystick Y-axis
- created actions for a number of Joystick-axis sections
- for each section create a vitual button with range (e.g -0.10 to -0.20)

The problem is that the virtual button should only trigger one key-press instead of being activated as long as the Joystick remains in a section. 

Is there a way to define a virtual button this way?
Or is there another way to synchronize Joystick and throttle movement?

**Comment by WhiteMagic** [comment]
In order to get a key activation, i.e. press and release you will have to use the macro action instead of remap to keyboard which I assume you're using. That will allow you to send the key down and key up events when entering the specified region.

You probably also will have to use the direction feature of the axis range bit, as I imagine you want to send A when passing through a section, say low to high, but on the way back so high to low you will want to send D.

Technically this probably could be done "simpler" with a custom module but as far as using purely the UI goes the way you started is the best one I can think of.

**Comment by bluddy** [comment]
(I'm going to apply this question to virtual buttons, which gives the most flexibility in Windows games:)

Does it really make sense to have a virtual button hold for as long as the axis is in a range? Most games take single button presses rather than long holds for most things. At the very least, it would be a good option to add: only push button when moving in range vs. holding button down while in range.

**Comment by WhiteMagic** [comment]
This behavior makes sense, based on what the remap action is supposed to do. The action is intended to be used to map a user's interaction with the physical device to a virtual one. As such the notion of a tap, i.e. quick press and release, is not what the action is attempting to provide.

Though this behavior can be a bit confusing it is intended. The usual solution for the tap behaviour is a macro as it's the most generic way of achieving this. It might make sense to have a different action or a toggle in the remap action to switch between the input forwarding and tap behaviour.
