### ISSUE TITLE
Mouse to Joystick. Possible?

### ISSUE THREAD

**Issue by spadino** [WhiteMagic/JoystickGremlin#98]
Hi! I'm impressed by your program. Quite the things I was looking for by years!!!
I would like to know if is it possible to remap a mouse to a vJoy, if not natively using a custom module. 
I would happily work on that if is it something possible to achieve...

**Comment by WhiteMagic** [comment]
Technically this is possible and the majority of the infrastructure needed for it is already present in windows_event_hook.py and event_handler.py. Essentially there are two main categories where things need to be added for mouse motions to be a valid input source for Gremlin:
- low level event reading and propagation (probably takes a few hours)
- figuring out how mouse motion will fit into things on the UI side as it is an entirely different modality (probably will take weeks)

Gremlin started out as a pure map joystick events to virtual ones and some extremely basic keyboard macro support. Gremlin by now can read mouse buttons and send them and can actually also send mouse motions. But I haven't even actually added mouse buttons to the list of physical inputs you can bind, though those are easy to handle as they're just buttons. The mouse motion itself is a weird beast as it:
- doesn't behave like other existing inputs
- actually has two modes of reporting information absolute and relative motion
- doesn't have true limits

Because of all of that I haven't really put much energy into trying to use a mouse as a mappable input device since exposing it in the UI is a massive headache I haven't found a good solution to yet.

**Comment by andreaspada** [comment]
Indeed, mouse it's a very weird beast, it behaves in a very specific manner. Anyway, now that you have addressed the use of vJoy devices as phisical inputs - #77 - there's no real need to create such UI. There are already existing options to map a mouse to vJoy, from Autohotkey to FreePIE, so we can easily use one of them in parallel!

**Comment by WhiteMagic** [comment]
Closing this for now as this is, if ever, very far down the road and there are other tools such as FreePie that are probably better suited for this, especially at this stage.
